ChangeLog.txt, lib/azure-storage.d.ts, lib/common/util/constants.js, lib/services/blob/blobservice.js, lib/services/file/fileservice.js, package.json, test/services/blob/blobservice-uploaddownload-tests.js, test/services/file/fileservice-uploaddownload-tests.js, typings/lib.es6/lib.es6.d.ts, typings/mocha/mocha.d.ts, typings/node-uuid/node-uuid.d.ts, typings/node/node.d.ts
=> Storage Client Library 0.8.0

CONTRIBUTING.md
- Fixes the link to the guidelines
- Changes updates to the current platform branding
This fixes #134
=> Fixes the dead link in CONTRIBUTING.md

CONTRIBUTING.md, ChangeLog.md, README.md, examples/samples/sassample.js, lib/azure-storage.js, lib/common/services/storageserviceclient.js, lib/common/signing/sharedkey.js, lib/common/util/constants.js, lib/services/blob/blobservice.js, lib/services/blob/blobutilities.js, lib/services/blob/internal/blockrangestream.js, lib/services/file/fileservice.js, lib/services/file/fileutilities.js, lib/services/queue/queueservice.js, lib/services/table/internal/odatahandler.js, lib/services/table/internal/requesthandler.js, lib/services/table/tableservice.js, package.json, test/recordings/blobservice-tests.nock.js, test/recordings/fileservice-tests.nock.js, test/recordings/tableservice-tests.nock.js, test/services/blob/blobservice-tests.js, test/services/blob/blobservice-uploaddownload-tests.js, test/services/file/fileservice-file-tests.js, test/services/file/fileservice-share-tests.js, test/services/file/fileservice-tests.js, test/services/table/tableservice-tests.js, typings/azure-storage/azure-storage.d.ts
=> Storage Client Library 1.1.0

BreakingChanges.md, ChangeLog.md, lib/azure-storage.js, lib/common/filters/retrypolicyfilter.js, lib/common/models/servicepropertiesresult.js, lib/common/services/storageserviceclient.js, lib/common/signing/sharedkey.js, lib/common/util/constants.js, lib/services/blob/blobservice.js, lib/services/file/fileservice.js, lib/services/queue/models/queuemessageresult.js, lib/services/queue/queueservice.js, lib/services/table/tableservice.js, package.json, test/common/filters/exponentialretrypolicyfilter-tests.js, test/recordings/queueservice-tests.nock.js, test/recordings/tableservice-tests.nock.js, test/services/blob/blobservice-tests.js, test/services/blob/blobservice-uploaddownload-tests.js, test/services/file/fileservice-file-tests.js, test/services/queue/queueservice-tests.js, test/services/table/tableservice-tests.js, typings/azure-storage/azure-storage.d.ts
=> Storage Client Library 1.3.0

lib/common/md5-wrapper/browser.js, lib/common/md5-wrapper/node.js, lib/common/md5-wrapper/package.json, lib/common/services/storageserviceclient.js, lib/common/streams/chunkstream.js, lib/common/streams/filereadstream.js, lib/common/util/constants.js, lib/common/util/util.js, lib/services/blob/blobservice.js, lib/services/file/fileservice.js, lib/services/table/internal/edmhandler.js, lib/services/table/internal/odatahandler.js, lib/services/table/models/batchresult.js, package.json
Fixed following browserify issues:
* Issue1: Enabling Md5 checking when uploading blobs will buffer all the trunks
* Issue6: Edge may crash after stream-http’s update using Fetch
* Issue7: 403 Authorization error when using Storage Key
* Issue9: IE - Number.isNaN is not a function
=> Browserify issues fix

browser/ChangeLog.md, browser/README.md, browser/samples/sample-blob.html, browser/samples/sample-file.html
- Update Readme.md about gzip recommendation;
- Update browsers validation version;
- Fixed missing 100% upload progress issue in blob sample for uploading blobs smaller than 32MB
- Added speedSummary code example in the blob & file samples
=> JavaScript Client Library 0.2.1-preview.3

ChangeLog.md, browser/ChangeLog.md, lib/common/common.core.js, lib/common/services/storageserviceclient.js, lib/common/streams/batchoperation.js, lib/common/streams/bufferstream.js, lib/common/streams/chunkallocator.js, lib/common/streams/chunkstream.js, lib/common/streams/filereadstream.js, lib/common/util/constants.js, lib/common/util/util.js, lib/services/blob/blobservice.core.js, package.json
* Optimized memory usage especially for uploading blobs with large block size.
=> Azure Storage Node.js Client Library v2.2.1

lib/services/table/tablequery.js
=> Fix the typo in the table query example.

README.md
This is a small change, but since the typo is in the first paragraph and pushed out to npm and other sites, it's worth fixing.
=> fix very minor typo

examples/blobuploader/app.js
This commit fixes problem with access blob `contentType` information in the current version
due to breaking changes:
https://git.io/vbpBD
Thanks!
=> Update `contentType` property access to latest sdk api

examples/blobuploader/package.json
As in commit title. Verified locally that it works (using remote connection string).
Thanks!
=> Update dependencies in ExpressJS blob uploader sample

lib/services/queue/queueservice.js
This PR fixes a scoping issue in the queue service.
=> Fixes bad scoping in Queue service

README.md
I recently used your Table Storage service and I could not find any reference in your documentation on **how to update/edit** an existing entries.
This is why I propose to add under the **Table Storage** section:
- an example of **replaceEntity**
- 2 mentioning of **insertOrReplaceEntity**
=> Adds replaceEntity and insertOrReplaceEntity

ChangeLog.md, lib/common/services/storageserviceclient.js, lib/common/util/constants.js, lib/services/blob/blobservice.core.js, lib/services/file/fileservice.core.js, lib/services/queue/queueservice.js, lib/services/table/tableservice.js, package.json, typings/azure-storage/azure-storage.d.ts
Add enableGlobalHttpAgent support.
=> Add enableGlobalHttpAgent support.

CONTRIBUTING.md
as PR's name says i fixed a typo
=> Fixed the heading Project Setup at CONTRIBUTING.md

BreakingChanges.md, README.md
=> Fix minor spelling issues in BreakingChanges.md, README.md

lib/services/blob/blobservice.core.js, typings/azure-storage/azure-storage.d.ts
I am seeing it limit the results when using ListBlobs.
=> remove comment about maxResults

typings/azure-storage/azure-storage.d.ts
=> Add `host` property to `StorageServiceClient`

CONTRIBUTING.md, README.md, package-lock.json
Run npm audit fix to fix vulnerabilities and remove dev branch info from Readme.
=> Fix vulnerabilities and deprecate dev branch for contribution.

index.html
=> Optimize doc to point to v12 repo.

ChangeLog.md, lib/common/util/constants.js, package-lock.json, package.json, test/services/blob/blobservice-tests.js, test/services/file/fileservice-file-tests.js, test/services/file/fileservice-share-tests.js
=> Preparing for 2.10.4 release

ChangeLog.md, lib/common/filters/retrypolicyfilter.js, lib/common/services/storageserviceclient.js, lib/common/util/constants.js, package-lock.json, package.json
Upgrade json-schema to 0.4.0 and fix an issue where customized retry interval doesn't take effact.
=> Upgrade json-schema to 0.4.0 and fix an issue where customized retry interval doesn't take effact.

ChangeLog.md, lib/common/util/constants.js, package-lock.json, package.json
Update dependency mark to make it use more recent version automatically.
=> Update dependency mark to make it use more recent version automatically.
