lib/common/filters/retrypolicyfilter.js

The reason for adding this is it is frequently seen when sending a multitude of requests in parallel.

Add 'EAI_AGAIN' as a default retry error code

---

package.json

Update `package.json` to include a `typings` reference to the type definition making this package more typings friendly. See #152, specifically this comment https://github.com/Azure/azure-storage-node/issues/152#issuecomment-235195913 for reference.
The work was mostly done by @SomaticIT & suggested by @mikesouth... I'm responding to @hasonmsft's last comment... sorry... I got impatient :)

add typings reference in package.json

---

typings/azure-storage/azure-storage.d.ts

If you use typescript and have the option "noImplicitAny" enabled, tsc will complain when trying to compile azure-storage, this can be easily fixed by adding the right type in 2 lines.

Updated azure-storage.d.ts for no implicit any

---

.gitignore

This is a small change useful when tests using real Azure Storage account
are run - the rule excludes unintentional staging of broken
tests artefacts.
Thanks!

Add rule to exclude tests artefacts from repo

---

gruntfile.js
package.json

This commit removes outdated NPM module for Grunt
with different module that replaced old one.
This will remove warning message when this library
is installed:
``` bash
npm WARN deprecated grunt-nsp-package@0.0.5: new api version released, use grunt-nsp instead
```
``` bash
➜  azure-storage-node git:(dev) grunt validate
Running "jshint:all" (jshint) task
>> 65 files lint free.
Running "validate-package" task
/Users/piotrblazejewicz/git/azure-storage-node/package.json
```
Thanks!

Replace Grunt plugin for NSP checks

---

BreakingChanges.md
ChangeLog.md
README.md
examples/blobuploader/app.js
examples/blobuploader/bin/server.js
examples/blobuploader/package.json
lib/common/filters/retrypolicyfilter.js
lib/common/services/storageserviceclient.js
lib/common/streams/speedsummary.js
lib/common/util/constants.js
lib/services/blob/blobservice.js
lib/services/file/fileservice.js
lib/services/queue/queueservice.js
package.json
test/common/filters/exponentialretrypolicyfilter-tests.js
test/common/util/util-tests.js
test/services/blob/blobservice-uploaddownload-tests.js
test/services/file/fileservice-share-tests.js

ALL
* Added `ENOTFOUND` for secondary endpoint and `ECONNREFUSED` to `RetryPolicyFilter`.
* Added support for `text/html` error response body.
BLOB
* Fixed the issue that the ChunkAllocator maxCount is aligned with parallelOperationThreadCount.
* Changed `/S` of SpeedSummary to `/s`.
* Fixed the issue that `BlobService.createBlockBlobFromText` will hang when passed `null` or `undefined` `text` argument. 
* Fixed the issue that `BlobService.createBlockBlobFromText` will always set `content-type` to `text/plain`.
QUEUE
* Allowed `QueueService.peekMessages` against secondary endpoint.
FILE
* Fixed the issue that the ChunkAllocator maxCount is aligned with parallelOperationThreadCount.
* Changed `/S` of SpeedSummary to `/s`.

Storage Client Library 1.4.0

---

typings/azure-storage/azure-storage.d.ts

Current definition defines the 3rd parameter as mandatory. This PR fixes this issue by marking this `host` parameter as optional.

Fix Typescript definition for createQueueService()

---

typings/azure-storage/azure-storage.d.ts

Created overload for method createTableService() to support examples without passed params. With current types you have to call it as createTableService(null, null, null) which is not JS/TS convenient.

Overloaded method createTableService()

---

typings/azure-storage/azure-storage.d.ts

The example in the documentation `fs.createReadStream(fileNameTarget).pipe(blobService.createWriteStreamToBlockBlob(containerName, blobName, { blockIdPrefix: 'block' }));` does not use a callback.

createWriteStreamToBlockBlob: `callback` should be optional

---

lib/services/blob/blobservice.core.js

Removed unicode character [0x2019](http://www.fileformat.info/info/unicode/char/2019/index.htm) from script file so it gets stored as `UTF-8` instead of `UTF-16` in Javascript engine.
Ref: https://github.com/Azure/azure-storage-node/pull/286

Removed utf16 character from script file

---

examples/samples/blobuploaddownloadsample.js

This replace use of `blob` proerty with `name` property for the
BlobResult object in sample source code.
See:
https://github.com/Azure/azure-storage-node/blob/dev/BreakingChanges.md
Use better name for result parameter with blob information
This remove problem with using differently scoped variables in source
code: one for globally (per-module) declared `blobAccess` variable,
the second used as name for result information parameter of
`createBlockBlobFromText` method callback
Thanks!

Fix uses of BlobResult object in sample source code

---

.jshintrc
browser/ChangeLog.md
browser/samples/sample-blob.html
browser/samples/sample-file.html
lib/common/common.browser.js
lib/common/streams/batchoperation.js
lib/common/streams/browserfilereadstream.js
lib/common/streams/chunkstream.js
lib/common/util/constants.js
lib/common/util/util.js
lib/common/util/validate.js
lib/services/blob/blobservice.browser.js
lib/services/blob/blobservice.core.js
lib/services/blob/blobservice.node.js
lib/services/file/fileservice.browser.js
lib/services/file/fileservice.core.js
lib/services/file/fileservice.node.js
package.json
typings/azure-storage/azure-storage.d.ts

Added browser specific APIs for uploading files and blobs from browser File objects:
-  `BlobService.createBlockBlobFromBrowserFile`
-  `BlobService.createPageBlobFromBrowserFile`
-  `BlobService.createAppendBlobFromBrowserFile`
-  `BlobService.appendFromBrowserFile`
-  `FileService.createFileFromBrowserFile`
Updated sample-blob.html and sample-file.html for new uploading APIs.
Added TypeScript definitions for new uploading APIs.
Dropped dependency to browserify-fs.

Added browser specific APIs for uploading files and blobs

---

package.json

Currently, we pull a version of request that comes with some known-to-be-vulnerable dependency -- see https://snyk.io/test/npm/azure-storage
Trying to address this, bumping request to 2.81.0

chore(package): update request to 2.81.0

---

README.md
lib/services/file/fileservice.core.js

Hi there! 👋 
Really dig using this Azure Storage SDK, thanks for the hard work in maintaining it 👍 
I wanted to use the `createFileFromStream` method recently from the File Storage Service of this SDK, and had to dig through the source code to figure out which parameters to supply. The very next day, I had a prominent Node community member coincidentally tweet at me asking about the same method and how to use it. I'm a Tech Evangelist for Microsoft so this kind of tweet is a common occurrence.
I went ahead and added an example in the docs for `createFileFromStream`. I didn't want `createFileFromText` to be lonely so I added an example for that too.
I hope the examples are to your liking; let me know if you'd like me to tweak any code or language. I wasn't sure whether or not to update the …

add additional File Storage examples

---

test/azure-tests.js

The env are always strings. The linter (or types) would detect this.
Thanks!

Fix type assignment in tests for env variables

---

lib/common/streams/filereadstream.js
package.json

See : https://snyk.io/vuln/npm:validator:20160218 and https://snyk.io/vuln/npm:validator:20180218
Suggested fix: update to validator >= 9.4.1
The type-coercion fix is a little blunt - i'm open to suggestions on how to do this better.

Update the request and validator package dependencies

---

ChangeLog.md
lib/common/util/constants.js
package.json

Bumped version of request module from ~2.83.0 to ^2.86.0 to solve a vulnerability issue #449

Bumped version of request module from ~2.83.0 to ^2.86.0 

---

lib/common/util/validate.js
test/common/storageservicesettingstests.js
test/common/util/validate-tests.js

Not sure if I changed the tests appropriately here; I had to [remove a test in storageservicetests.js](https://github.com/Azure/azure-storage-node/commit/4727325fe97e729bd92599b4c7a65ae7a78c6827#diff-f06b7e1d10ed68e066b258381d1d2abdL100) because it was verifying an exception that will no longer be thrown, and I didn't know what to replace the test input with there that would still fail with the new requirements, but still allow TLDs.
This resolves #436.

Allow non TLD hosts

---

lib/services/table/tableservice.js

This threw me for a loop for about 30 minutes. The documentation says result.entitites will contain the entities returned from the query, but the code (line 849) uses result.entries.
http://azure.github.io/azure-storage-node/TableService.html#queryEntities
It might make more sense for everything to be entities, but unless both entities and entries are in the object, that would be a breaking change.
(Also, https://cla.azure.com in the guidelines is timing out, where (unencrypted/port 80) http://cla.azure.com redirect to https://cla.opensource.microsoft.com/)

Change queryTable doc to use result.entries

---

typings/azure-storage/azure-storage.d.ts

Added missing declarations to 'azure-storage.d.ts' file. Two methods 'listBlobDirectoriesSegmented' and 'listBlobDirectoriesSegmentedWithPrefix' were present in 'blobservice.core.js' but not represented in TypeScript declarations file as described in issue #504

Add missing declarations to ts

---

lib/services/table/tableservice.js

Hi, thanks for this SDK. This is a minor fix for the following issue:
Fixes: https://github.com/Azure/azure-storage-node/issues/517
Checks for null responseObject.response before attempting to access statusCode property.
Tests pass locally.

Address uncaught TypeError in table service

---

lib/services/blob/blobservice.core.js

Just a small typo fix, I discovered while browsing the code.

Fix typo in blobservice.core private method name

---

README.md

Update the docs link in the readme

---

package-lock.json
package.json

Component Governance from DevOps complains of the underscore dependency in azure-sdk-for-js repo.
- Pulled in by event-processor-host since it depends on azure-storage
- Need to update underscore to ^1.12.1 to fix the problem

Update underscore to 1.12.1

---

README.md

Changes:
- We are close to releasing the Tables SDK, so updating the README of the azure-storage package with the right pointers.
- Also, took this opportunity to add the suggested standard text we use for older packages that are being replaced
cc @joheredi, @XiaoningLiu, @EmmaZhu, @vinjiang

Update readme with links to the new Tables SDK

---

README.md

This PR replaces the bulleted list of Azure services with a comma separated one to bring more attention to the following note on newer packages.
Before:
After:

Bring more attention to the note on newer packages

---

README.md

This PR has the following changes:
- Remove "Microsoft" from the title as it is redundant given that we have "Azure"
- Add the term "legacy" to the title and when referring to the azure-storage package

Indicate that azure-storage is legacy package
